"""'Categorytableadded'

Revision ID: ff564dd3947e
Revises: 9a1332118246
Create Date: 2023-01-04 22:13:39.685648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff564dd3947e'
down_revision = '9a1332118246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('Category_id', sa.Integer(), nullable=False),
    sa.Column('Category_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
